<?php

/**
 * @file
 * S3WaaS theme and master data creation system.
 */

use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_modules_installed().
 */
function s3waas_modules_installed($modules)
{
  $categories_vocabulary = 'notice'; // Vocabulary machine name
  $categories = ['Notice', 'Recruitment', 'Tender', 'Event']; // List of terms
  foreach ($categories as $category) {
    Term::create([
      'parent' => [],
      'name' => $category,
      'vid' => $categories_vocabulary,
    ])->save();
  }
}
