<?php

/**
 * @file
 * Render content with tabs and other display styles
 */

use Drupal\Core\Routing\RouteMatchInterface;

// Store quicktabs preprocess theme functions in a separate .inc file.
\Drupal::moduleHandler()->loadInclude('quicktabs', 'inc', 'quicktabs.theme');

/**
 * Implements hook_help().
 */
function quicktabs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'quicktabs.admin':
      return '<p>' . t('Each QuickTabs instance has a corresponding block that is managed on the <a href="@blocks">blocks administration page</a>.', array('@blocks' => \Drupal::Url('block.admin_display'))) . '</p>';
  }
}

/**
 *  Implements hook_theme().
 */
function quicktabs_theme($existing, $type, $theme, $path) {
  return array(
    'quicktabs_block_content' => array(
      'variables' => array('title' => NULL, 'block' => NULL, 'classes' => NULL, 'id' => NULL),
      'template' => 'quicktabs-block-content',
    ),
    'quicktabs_view_quicktabs' => array(
      'file' => 'quicktabs.theme.inc',
    ),
  );
}
